version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: stryktips-db
    environment:
      POSTGRES_USER: stryktips
      POSTGRES_PASSWORD: stryktips
      POSTGRES_DB: stryktips
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stryktips"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: stryktips-app
    environment:
      DATABASE_URL: postgresql://stryktips:stryktips@postgres:5432/stryktips
      LOG_LEVEL: INFO
      DEBUG: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
