"""Add football history tables

Revision ID: 9544f82e6b16
Revises: 
Create Date: 2025-10-25 19:42:28.858623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9544f82e6b16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use JSON for SQLite, JSONB for PostgreSQL
    from alembic import context
    json_type = sa.JSON() if 'sqlite' in str(context.get_bind().engine.url) else postgresql.JSONB(astext_type=Text())

    op.create_table('competitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_code'), 'competitions', ['code'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_normalized', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('external_refs', json_type, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name_normalized'), 'teams', ['name_normalized'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('external_refs', json_type, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'name', name='uq_season_competition_name')
    )
    op.create_index('ix_season_competition_year', 'seasons', ['competition_id', 'year_start', 'year_end'], unique=False)
    op.create_index(op.f('ix_seasons_competition_id'), 'seasons', ['competition_id'], unique=False)
    op.create_table('football_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('date_utc', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('external_refs', json_type, nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_ts', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'matchday', 'home_team_id', 'away_team_id', name='uq_match_season_matchday_teams')
    )
    op.create_index(op.f('ix_football_matches_away_team_id'), 'football_matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_football_matches_date_utc'), 'football_matches', ['date_utc'], unique=False)
    op.create_index(op.f('ix_football_matches_home_team_id'), 'football_matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_football_matches_season_id'), 'football_matches', ['season_id'], unique=False)
    op.create_index(op.f('ix_football_matches_venue_id'), 'football_matches', ['venue_id'], unique=False)
    op.create_index('ix_match_season_date', 'football_matches', ['season_id', 'date_utc'], unique=False)
    op.create_index('ix_match_teams', 'football_matches', ['home_team_id', 'away_team_id'], unique=False)
    op.create_table('football_standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('table', json_type, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_football_standings_season_id'), 'football_standings', ['season_id'], unique=False)
    op.create_index('ix_standing_season_matchday', 'football_standings', ['season_id', 'matchday'], unique=True)
    op.create_table('football_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('player', sa.String(length=200), nullable=True),
    sa.Column('detail', json_type, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['football_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_match_minute', 'football_events', ['match_id', 'minute'], unique=False)
    op.create_index('ix_event_type', 'football_events', ['type'], unique=False)
    op.create_index(op.f('ix_football_events_match_id'), 'football_events', ['match_id'], unique=False)
    op.create_index(op.f('ix_football_events_team_id'), 'football_events', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_football_events_team_id'), table_name='football_events')
    op.drop_index(op.f('ix_football_events_match_id'), table_name='football_events')
    op.drop_index('ix_event_type', table_name='football_events')
    op.drop_index('ix_event_match_minute', table_name='football_events')
    op.drop_table('football_events')
    op.drop_index('ix_standing_season_matchday', table_name='football_standings')
    op.drop_index(op.f('ix_football_standings_season_id'), table_name='football_standings')
    op.drop_table('football_standings')
    op.drop_index('ix_match_teams', table_name='football_matches')
    op.drop_index('ix_match_season_date', table_name='football_matches')
    op.drop_index(op.f('ix_football_matches_venue_id'), table_name='football_matches')
    op.drop_index(op.f('ix_football_matches_season_id'), table_name='football_matches')
    op.drop_index(op.f('ix_football_matches_home_team_id'), table_name='football_matches')
    op.drop_index(op.f('ix_football_matches_date_utc'), table_name='football_matches')
    op.drop_index(op.f('ix_football_matches_away_team_id'), table_name='football_matches')
    op.drop_table('football_matches')
    op.drop_index(op.f('ix_seasons_competition_id'), table_name='seasons')
    op.drop_index('ix_season_competition_year', table_name='seasons')
    op.drop_table('seasons')
    op.drop_table('venues')
    op.drop_index(op.f('ix_teams_name_normalized'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_competitions_code'), table_name='competitions')
    op.drop_table('competitions')
    # ### end Alembic commands ###
